#!/usr/bin/env bash
# Write a Bash script that:Creates the file /var/run/myscript.pid W its PID

remove() {
  rm /var/run/myscript.pid
  exit
}

echo "$$" > /var/run/myscript.pid

while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "Y U no love me?!"' SIGINT
  trap 'echo "I hate the kill command" && remove' SIGTERM
  trap 'remove' SIGQUIT
done
