#!/usr/bin/env bash
# Writing a Bash script that displays Best School 10 times with while loop

counter=0

while [ $counter -lt 10 ]; do
	echo "Best School"
	if [ $counter -eq 8 ]; then
		echo "Hi"
	fi
	counter=$((counter + 1))
done
