#!/usr/bin/env bash
# Writing a Bash script that displays time

counter=0

while [ $counter -lt 13 ]; do
	echo "Hour: $counter"
	minutes=1
	while [ $minutes -lt 60 ]; do
		echo $minutes
		((minutes++))
	done
	counter=$((counter + 1))
done
