#!/usr/bin/env bash
# Script that configures an Ubuntu server with the below requirements
# localhost resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8

cp /etc/hosts /etc/hosts.bak
sed -i '/facebook.com/d' /etc/hosts.bak
sed -i 's/127\.0\.0\.1/127.0.0.2/' /etc/hosts.bak
echo "8.8.8.8	facebook.com" | sudo tee -a /etc/hosts.bak > /dev/null
cp -f /etc/hosts.bak /etc/hosts
